import random
import numpy as np
import mysql.connector
import pandas as pd
import csv

# źródło: https://motointegrator.com/pl/pl/uslugi

services_moto = [
    "Przegląd motocykla",
    "Serwis podstawowy motocykla",
    "Serwis gaźników motocyklowych (regulacja i czyszczenie)",
    "Diagnostyka komputerowa motocykli",
    "Diagnostyka i naprawa układów zawieszeń motocykli",
    "Diagnostyka i naprawa układów napędowych motocykli",
    "Lakierowanie motocykli",
    "Naprawa motocykli powypadkowych",
    "Tuning motocykli",
    "Tuning mechaniczny i elektroniczny motocykli",
    "Programowanie i modyfikacje sterowników ECU",
    "Montaż akcesoriów motocyklowych",
    "Diagnostyka i naprawa układu elektrycznego motocykla",
    "Diagnostyka i naprawa elementów elektronicznych motocykli",
    "Serwis i naprawa motocykli cross i enduro",
    "Serwis i naprawa pojazdów ATV/UTV",
    "Wymiana przedniej opony w motocyklu",
    "Serwis skuterów i motorowerów",
    "Wymiana łańcucha i zębatek w motocyklu",
    "Wymiana tarcz i klocków hamulcowych w motocyklu",
    "Wymiana oleju i filtra oleju w motocyklu",
    "Wymiana tylnej opony w motocyklu",
    "Wymiana klocków hamulcowych w motocyklu",
    "Wymiana akumulatora w motocyklu"
]


prices_moto = {
    "Przegląd motocykla": 150,
    "Serwis podstawowy motocykla": 200,
    "Serwis gaźników motocyklowych (regulacja i czyszczenie)": 100,
    "Diagnostyka komputerowa motocykli": 80,
    "Diagnostyka i naprawa układów zawieszeń motocykli": 250,
    "Diagnostyka i naprawa układów napędowych motocykli": 300,
    "Lakierowanie motocykli": 400,
    "Naprawa motocykli powypadkowych": 500,
    "Tuning motocykli": 350,
    "Tuning mechaniczny i elektroniczny motocykli": 450,
    "Programowanie i modyfikacje sterowników ECU": 200,
    "Montaż akcesoriów motocyklowych": 100,
    "Diagnostyka i naprawa układu elektrycznego motocykla": 150,
    "Diagnostyka i naprawa elementów elektronicznych motocykli": 180,
    "Serwis i naprawa motocykli cross i enduro": 300,
    "Serwis i naprawa pojazdów ATV/UTV": 350,
    "Wymiana przedniej opony w motocyklu": 80,
    "Serwis skuterów i motorowerów": 150,
    "Wymiana łańcucha i zębatek w motocyklu": 120,
    "Wymiana tarcz i klocków hamulcowych w motocyklu": 150,
    "Wymiana oleju i filtra oleju w motocyklu": 50,
    "Wymiana tylnej opony w motocyklu": 70,
    "Wymiana klocków hamulcowych w motocyklu": 100,
    "Wymiana akumulatora w motocyklu": 150
}

with open('uslugi_motocyklowe.csv', mode='w', newline='', encoding='utf-8') as file:
    writer = csv.writer(file)
    writer.writerow(['Usluga', 'Cena'])
    for usluga in services_moto:
        writer.writerow([usluga, prices_moto.get(usluga, 'Brak danych')])

services_car = [
    "Wymiana oleju i filtra oleju",
    "Wymiana filtra powietrza",
    "Wymiana filtra paliwa",
    "Wymiana filtra kabinowego",
    "Hamulce",
    "Naprawa układu hamulcowego",
    "Wymiana klocków hamulcowych",
    "Wymiana tarcz hamulcowych",
    "Wymiana szczęk hamulcowych",
    "Wymiana cylinderków hamulcowych w samochodzie",
    "Wymiana bębnów hamulcowych",
    "Wymiana tarcz kotwicznych bębnów hamulcowych",
    "Wymiana rozpieraczy",
    "Wymiana linki hamulca ręcznego",
    "Wymiana przewodów hamulcowych elastycznych",
    "Wymiana przewodów hamulcowych metalowych",
    "Wymiana pompy hamulcowej",
    "Wymiana płynu hamulcowego",
    "Naprawa ABS",
    "Wymiana pompy ABS",
    "Wymiana czujnika ABS",
    "Weryfikacja układu hamulcowego",
    "Zawieszenie",
    "Wymiana drążka kierowniczego",
    "Wymiana końcówki drążka kierowniczego",
    "Wymiana maglownicy",
    "Wymiana zwrotnicy koła",
    "Wymiana krzyżaka kolumny kierowniczej",
    "Wymiana pompy wspomagania",
    "Wymiana płynu wspomagania kierownicy",
    "Naprawa układu kierowniczego",
    "Wymiana osłony elastycznej przekładni kierowniczej",
    "Ustawienie geometrii i zbieżności kół",
    "Wymiana stabilizatora",
    "Wymiana łącznika stabilizatora",
    "Wymiana tulejek gumy stabilizatora",
    "Wymiana wahacza",
    "Wymiana silentblocku wahacza",
    "Wymiana sworznia wahacza",
    "Wymiana amortyzatora",
    "Wymiana łożyska amortyzatora",
    "Wymiana poduszki amortyzatora",
    "Wymiana osłony elastycznej amortyzatora",
    "Wymiana sprężyn zawieszenia",
    "Wymiana kolumny MacPhersona",
    "Wymiana piasty",
    "Wymiana łożyska w kole",
    "Naprawa zawieszenia",
    "Weryfikacja układu kierowniczego",
    "Diagnostyka zawieszenia",
    "Silnik",
    "Wymiana paska wielorowkowego",
    "Wymiana paska rozrządu",
    "Wymiana łańcucha rozrządu",
    "Wymiana płynu chłodniczego",
    "Wymiana chłodnicy silnika",
    "Wymiana czujnika temperatury",
    "Wymiana termostatu",
    "Naprawa wentylatora chłodnicy",
    "Wymiana nagrzewnicy",
    "Wymiana przewodów układu chłodzenia w samochodzie",
    "Wymiana pompy wody",
    "Wymiana sprzęgła wentylatora chłodnicy (wiskozy)",
    "Wymiana rezystora nagrzewnicy",
    "Wymiana czujnika / termowłącznika wentylatora",
    "Naprawa układu chłodzenia",
    "Wymiana kolektora dolotowego",
    "Wymiana uszczelki kolektora dolotowego",
    "Wymiana przewodu dolotowego",
    "Wymiana uszczelki przewodu dolotowego",
    "Wymiana przepływomierza - czujnika masy powietrza",
    "Naprawa układu dolotowego",
    "Wymiana wtryskiwaczy",
    "Wymiana pompowtryskiwaczy",
    "Wymiana pompy paliwa",
    "Wymiana pompy wtryskowej",
    "Wymiana zbiornika paliwa",
    "Wymiana przewodów paliwowych",
    "Czyszczenie układu paliwowego",
    "Naprawa układu paliwowego",
    "Wymiana uszczelki pokrywy zaworów",
    "Wymiana uszczelki miski olejowej",
    "Wymiana uszczelki pod głowicą",
    "Wymiana uszczelniaczy zaworowych",
    "Wymiana napinacza paska klinowego",
    "Wymiana linki gazu",
    "Wymiana koła pasowego",
    "Wymiana rolki napinacza",
    "Wymiana rolki napinającej",
    "Wymiana silnika regulacji biegu jałowego",
    "Wymiana rozrządu",
    "Wymiana zaworów",
    "Wymiana pierścieni tłokowych",
    "Wymiana sworznia tłokowego",
    "Wymiana panewek korbowodowych",
    "Wymiana panewek",
    "Wymiana tłoków",
    "Wymiana wałka rozrządu",
    "Wymiana wału korbowego",
    "Planowanie głowicy",
    "Generalny remont silnika",
    "Naprawa silnika",
    "Wymiana koła zamachowego",
    "Wymiana turbosprężarki",
    "Weryfikacja silnika",
    "Weryfikacja układu chłodzenia",
    "Weryfikacja układu paliwowego",
    "Naprawa wtryskiwacza paliwa",
    "Regeneracja głowic samochodowych",
    "Układ napędowy",
    "Wymiana półosi",
    "Wymiana uszczelniacza półosi napędowej",
    "Wymiana przegubu",
    "Wymiana osłony przegubu",
    "Naprawa układu napędowego",
    "Wymiana oleju w mechanizmie różnicowym",
    "Naprawa wałów i mostów napędowych",
    "Weryfikacja układu napędowego",
    "Naprawa skrzyń biegów",
    "Wymiana oleju w skrzyni automatycznej",
    "Wymiana oleju i filtra w skrzyni manualnej",
    "Wymiana sprzęgła",
    "Wymiana kompletnego sprzęgła z dwumasowym kołem zamachowym",
    "Wymiana tarczy sprzęgła",
    "Wymiana docisku sprzęgła",
    "Wymiana łożyska oporowego sprzęgła",
    "Wymiana linki sprzęgła",
    "Wymiana wysprzęglika",
    "Wymiana pompy sprzęgła",
    "Wymiana oleju i filtra hydraulicznego w skrzyni automatycznej",
    "Naprawa automatycznej skrzyni biegów",
    "Naprawa manualnej skrzyni biegów",
    "Układ wydechowy",
    "Wymiana kolektora wydechowego",
    "Wymiana uszczelki kolektora wydechowego",
    "Wymiana kompletnego tłumika",
    "Wymiana tłumika środkowego",
    "Wymiana tłumika końcowego",
    "Wymiana tłumika drgań",
    "Spawanie tłumika",
    "Uszczelnianie wydechu",
    "Naprawa wieszaków tłumika",
    "Wymiana katalizatora",
    "Wymiana sondy lambda",
    "Wymiana filtra DPF",
    "Naprawa układu wydechowego",
    "Wymiana zaworu EGR",
    "Weryfikacja układu wydechowego",
    "Regeneracja filtra cząstek stałych DPF / FAP",
    "Regeneracja części samochodowych",
    "Regeneracja pompy hamulcowej",
    "Regeneracja pompy ABS",
    "Regeneracja przekładni kierowniczej",
    "Regeneracja pompy wspomagania",
    "Regeneracja wtryskiwaczy benzynowych i diesla",
    "Regeneracja pompy wtryskowej",
    "Regeneracja turbosprężarki",
    "Regeneracja alternatora",
    "Regeneracja rozrusznika",
    "Regeneracja zacisków hamulcowych",
    "Elektronika",
    "Serwis Akumulatorów",
    "Wymiana akumulatora",
    "Sprawdzenie ładowania akumulatora",
    "Test obciążeniowy akumulatora",
    "Dostawa akumulatora z wymianą",
    "Darmowy test akumulatora",
    "Diagnostyka",
    "Kasowanie kodów błędów",
    "Oświetlenie",
    "Wymiana żarówki reflektora (Przód)",
    "Ustawienie świateł",
    "Wymiana tylnego klosza",
    "Wymiana silnika regulacji wysokości świateł",
    "Wymiana żarówki tablicy rejestracyjnej",
    "Elektryka samochodowa",
    "Wymiana żarówki klosza (Tył)",
    "Wymiana żarówki ksenonowej",
    "Montaż czujników parkowania",
    "Wymiana zegarów deski rozdzielczej",
    "Wymiana świec zapłonowych/żarowych",
    "Wymiana przewodów zapłonowych",
    "Wymiana cewki zapłonowej",
    "Naprawa modułu zapłonowego",
    "Wymiana kopułki rozdzielacza",
    "Naprawa rozdzielacza",
    "Wymiana rozrusznika",
    "Wymiana alternatora",
    "Montaż kamery cofania",
    "Wymiana bezpieczników",
    "Wymiana silniczka wycieraczek",
    "Wymiana pompy spryskiwacza",
    "Wymiana przerywnika kierunkowskazów",
    "Montaż elektrycznego ogrzewania postojowego DEFA",
    "Montaż spalinowego ogrzewania postojowego typu Webasto",
    "Wymiana mechanizmu podnoszenia szyby",
    "Wymiana stacyjki",
    "Naprawa i wymiana zamków",
    "Wymiana cięgna wycieraczki",
    "Montaż siłowników centralnego zamka",
    "Wymiana nagrzewnicy silnika",
    "Naprawa liczników samochodowych",
    "Naprawa systemu wspomagającego hamowanie - ABS, BAS, EBD",
    "Naprawa systemu zapobiegającego poślizgom - ASR, ESP, DSR, RSC, VSA",
    "Naprawa systemu wspomagającego jazdę - TSR, ACC, BLIS, AFS, LDW, HHC, SBR",
    "Naprawa systemu wspomagającego układ napędowy - ACD, EDS",
    "Naprawa systemu bezpieczeństwa podczas wypadku - AHR, ACS",
    "Elektryk samochodowy - naprawa elektroniki",
    "Wymiana czujnika biegu jałowego",
    "Wymiana czujnika ciśnienia oleju",
    "Wymiana czujnika ciśnienia paliwa",
    "Wymiana czujnika ciśnienia powietrza w kole TPMS",
    "Wymiana czujnika ciśnienia spalin",
    "Wymiana czujnika ciśnienia w kolektorze ssącym",
    "Wymiana czujnika ciśnienia w układzie hamulcowym",
    "Wymiana czujnika ciśnienia modułu tłoczącego DeNOx",
    "Wymiana czujnika Halla aparatu zapłonowego i wału korbowego",
    "Wymiana czujnika i nadajnika układu sterowania wtryskiem paliwa",
    "Wymiana czujnika impulsów / impulsatora",
    "Wymiana czujnika klimatyzacji",
    "Wymiana czujnika ciśnienia gazu (LPG)",
    "Wymiana czujnika nachylenia, układu alarmowego",
    "Wymiana czujnika obrotomierza",
    "Wymiana czujnika oleju",
    "Wymiana czujnika otwierania drzwi",
    "Wymiana czujnika położenia pedału gazu",
    "Wymiana czujnika położenia pedału sprzęgła",
    "Wymiana czujnika położenia przepustnicy",
    "Wymiana czujnika położenia wałka rozrządu",
    "Wymiana czujnika położenia wału korbowego",
    "Wymiana czujnika poziomu oleju silnikowego",
    "Wymiana czujnika poziomu paliwa",
    "Wymiana czujnika poziomu płynu chłodzącego",
    "Wymiana czujnika poziomu płynu hamulcowego",
    "Wymiana czujnika poziomu płynu spryskiwacza",
    "Wymiana czujnika poziomu zawieszenia pneumatycznego",
    "Wymiana czujnika przesunięcia pedału hamulca",
    "Wymiana czujnika skrętu koła kierownicy",
    "Wymiana czujnika skrzyni biegów",
    "Wymiana czujnika spalania stukowego",
    "Wymiana czujnika szybkości",
    "Wymiana czujnika świateł stop",
    "Wymiana czujnika temperatury wewnętrznej klimatyzacji",
    "Wymiana czujnika temperatury oleju",
    "Wymiana czujnika temperatury paliwa",
    "Wymiana czujnika temperatury płynu chłodzącego",
    "Wymiana czujnika temperatury powietrza wlotowego",
    "Wymiana czujnika temperatury spalin",
    "Wymiana czujnika temperatury zewnętrznej",
    "Wymiana czujnika tlenków azotu NOx",
    "Wymiana czujnika układu chłodzenia",
    "Wymiana czujnika zużycia klocka hamulcowego",
    "Wymiana czujnika/przekaźnika",
    "Weryfikacja instalacji elektrycznej",
    "Zaawansowane systemy wspomagania kierowcy (ADAS)",
    "Tempomat montaż i naprawa",
    "Kalibracja radarów",
    "Ustawienia kamery samochodowej",
    "System wspomagający ruszanie pod górę (HAS)",
    "Elektroniczny system bezpieczeństwa czynnego (Hill Descent Control)",
    "System stabilizujący tor jazdy samochodu (ESC)",
    "Czujniki ciśnienia w oponach TPMS - wymiana",
    "Naprawa i wymiana opon",
    "Wymiana opon Runflat - dowolna felga",
    "Wymiana opon z czujnikiem TPMS",
    "Wymiana opon i wulkanizacja",
    "Naprawa opon",
    "Wymiana zaworków",
    "Wyważanie kół",
    "Geometria kół 3D",
    "Mobilna wulkanizacja 24h",
    "Naprawa felg",
    "Renowacja felg stalowych",
    "Renowacja felg aluminiowych",
    "Diagnostyka komputerowa samochodu",
    "Przegląd podstawowy",
    "Przegląd rozszerzony",
    "Przegląd samochodu przed zakupem",
    "Przegląd letni",
    "Przegląd zimowy",
    "Przegląd samochodu przed podróżą",
    "Pomiar punktów bazowych nadwozia",
    "Diagnostyka samochodu - 22 punkty kontrolne",
    "Diagnostyka samochodu - 29 punktów kontrolnych",
    "Przegląd przed wakacjami",
    "Stacja Kontroli Pojazdów",
    "Przegląd - okresowe badanie techniczne (SKP)",
    "Klimatyzacja",
    "Serwis klimatyzacji",
    "Przegląd klimatyzacji",
    "Napełnienie klimatyzacji",
    "Sprawdzenie szczelności układu klimatyzacji - ciśnieniowe",
    "Sprawdzenie szczelności układu klimatyzacji - ultrafiolet",
    "Odgrzybianie klimatyzacji",
    "Ozonowanie klimatyzacji",
    "Wymiana oleju w sprężarce klimatyzacji",
    "Serwis klimatyzacji samochodowej",
    "Naprawa układu klimatyzacji",
    "Blacharstwo i lakiernictwo",
    "Wymiana elementów blacharskich",
    "Wymiana zderzaka",
    "Wymiana błotnika",
    "Wymiana pokrywy silnika",
    "Wymiana klapy bagażnika",
    "Wymiana drzwi przednich",
    "Wymiana drzwi tylnych",
    "Wymiana dachu",
    "Wymiana ćwiartki przedniej",
    "Wymiana ćwiartki tylnej",
    "Wymiana progu",
    "Wymiana pasa przedniego",
    "Wymiana pasa tylnego",
    "Wymiana reflektora",
    "Wymiana kierunkowskazu",
    "Wymiana lusterka",
    "Wymiana nadkola",
    "Wymiana podłogi pod silnikiem",
    "Naprawa zderzaka",
    "Naprawa błotnika",
    "Naprawa pokrywy silnika",
    "Naprawa tylnej klapy",
    "Naprawa drzwi przednich",
    "Naprawa drzwi tylnych",
    "Naprawa dachu",
    "Naprawa przedniej ćwiartki",
    "Naprawa tylnej ćwiartki",
    "Naprawa progu",
    "Naprawa pasa przedniego",
    "Naprawa pasa tylnego",
    "Wymiana teleskopu pokrywy silnika lub klapy bagażnika",
    "Wyciąganie wgniotek",
    "Konserwacja podwozia / zabezpieczenie antykorozyjne podwozia",
    "Lakierowanie elementów blacharskich",
    "Lakiernik samochodowy - lakierowanie całego nadwozia",
    "Lakierowanie zderzaka przedniego",
    "Lakierowanie zderzaka tylnego",
    "Lakierowanie błotnika przedniego",
    "Lakierowanie błotnika tylnego",
    "Malowanie pokrywy silnika",
    "Lakierowanie tylnej klapy",
    "Lakierowanie drzwi przednich",
    "Lakierowanie drzwi tylnych",
    "Lakierowanie dachu",
    "Lakierowanie ćwiartki przedniej",
    "Lakierowanie ćwiartki tylnej",
    "Malowanie progu",
    "Lakierowanie pasa przedniego",
    "Lakierowanie pasa tylnego",
    "Lakierowanie lusterka",
    "Zabezpieczenie antykorozyjne",
    "Wymiana szyb",
    "Wymiana czujnika opadów deszczu",
    "Wymiana szyby przedniej",
    "Wymiana szyby tylnej",
    "Wymiana, naprawa szyberdachu",
    "Wymiana szkła lusterka",
    "Wymiana szyby karoseryjnej",
    "Naprawa szyb",
    "Naprawa podgrzewania szyby przedniej / tylnej",
    "Wymiana szyby bocznej - otwieranej",
    "Naprawa pęknięć/odprysków szyb",
    "Czyszczenie auta",
    "Przyciemnianie szyb",
    "Przyciemnianie szyby szyberdachu",
    "Niewidzialna wycieraczka",
    "Regeneracja reflektorów",
    "Czyszczenie wnętrza samochodu",
    "Polerowanie i woskowanie samochodu",
    "Oklejanie samochodu",
    "Pranie tapicerki samochodowej",
    "Polerowanie samochodu",
    "Myjnia samochodowa",
    "Myjnia parowa",
    "Myjnia bezdotykowa",
    "Myjnia ręczna",
    "Myjnia samoobsługowa",
    "Pranie tapicerki",
    "Uruchomienie samochodu w zimie u klienta",
    "Awaryjne otwieranie samochodu",
    "Serwis instalacji gazowych LPG",
    "Montaż instalacji LPG",
    "Regulacja LPG",
    "Wymiana elektrozaworu LPG",
    "Wymiana filtra LPG",
    "Wymiana mieszalnika LPG",
    "Wymiana przewodów LPG",
    "Wymiana reduktora LPG",
    "Wymiana zaworu LPG",
    "Wymiana wlewu LPG",
    "Wymiana wtryskiwacza LPG",
    "Wymiana parownika LPG",
    "Lubryfikacja LPG",
    "Legalizacja zbiornika LPG",
    "Wymiana butli LPG",
    "Serwis instalacji gazowych CNG",
    "Regulacja CNG",
    "Wymiana wtryskiwacza CNG",
    "Montaż instalacji CNG z homologacją",
    "Wymiana reduktora CNG",
    "Wymiana przewodów CNG",
    "Wymiana elektrozaworu CNG",
    "Wymiana mieszalnika CNG",
    "Wymiana wlewu CNG",
    "Wymiana zaworu CNG",
    "Wymiana parownika CNG",
    "Wymiana zbiornika CNG",
    "Lubryfikacja CNG",
    "Legalizacja zbiornika CNG",
    "Modyfikacje/Tuning",
    "Tuning samochodów i modyfikacje sportowe",
    "Pompowanie opon azotem",
    "Montaż Power Boxów podnoszących moc",
    "Podniesienie mocy silnika",
    "Montaż sportowego filtra powietrza",
    "Montaż sportowego filtra oleju",
    "Montaż opon wyczynowych",
    "Obsługa hamulców sportowych",
    "Montaż sportowych tarcz hamulcowych",
    "Montaż sportowych klocków hamulcowych",
    "Montaż sportowego płynu hamulcowego",
    "Montaż przewodów hamulcowych w oplocie",
    "Obsługa zawieszenia sportowego",
    "Montaż sportowych amortyzatorów",
    "Obniżenie samochodu",
    "Montaż sprężyn do zwiększonego obciążenia",
    "Montaż rozpórek",
    "Montaż sportowych stabilizatorów",
    "Montaż sportowych tulei zawieszenia",
    "Montaż sportowego zestawu zawieszenia",
    "Montaż sportowych wskaźników",
    "Instalacja podtlenku azotu",
    "Montaż oświetlenia ksenonowego",
    "Montaż kutych tłoków",
    "Montaż wyczynowych panewek",
    "Montaż wyczynowych zaworów",
    "Montaż sportowego wałka rozrządu",
    "Montaż sportowych świec zapłonowych",
    "Montaż sportowych przewodów zapłonowych",
    "Montaż sportowego układu chłodzenia",
    "Adaptacja regulatora ciśnienia paliwa",
    "Montaż sportowej pompy paliwa",
    "Montaż sportowego układu wydechowego",
    "Montaż sportowego układu przeniesienia napędu",
    "Wymiana sportowego oleju silnikowego",
    "Wymiana sportowego oleju przekładniowego",
    "Wymiana sportowego płynu chłodzącego",
    "Detale samochodu",
    "Dekarbonizacja (wodorowanie) silnika",
    "Hamownia samochodowa",
    "Tapicer samochodowy",
    "Chiptuning / mapowanie silnika",
    "Akcesoria samochodowe",
    "Montaż belek dachowych",
    "Montaż boxu dachowego",
    "Montaż haka holowniczego",
    "Wymiana pasa bezpieczeństwa",
    "Wymiana piór wycieraczek",
    "Wymiana Gaśnicy",
    "Kodowanie / programowanie kluczyka",
    "Car Audio",
    "Montaż radia",
    "Montaż nawigacji",
    "Montaż głośników samochodowych",
    "Wygłuszenie samochodu",
    "Podłączenie wzmacniacza samochodowego",
    "Podłączenie subwoofera",
    "Montaż anten",
    "Aktualizacja nawigacji",
    "Montaż zestawu głośnomówiącego",
    "Montaż systemu GPS",
    "Pojazdy elektryczne i hybrydowe",
    "Układy samochodów elektrycznych",
    "Kontrola akumulatora wysokonapięciowego pojazdu elektrycznego",
    "Regeneracja baterii w aucie elektrycznym",
    "Diagnostyka silnika elektrycznego",
    "Naprawa przekładni w aucie elektrycznym",
    "Wymiana falownika w aucie elektrycznym",
    "Naprawa silnika w aucie elektrycznym",
    "Wymiana gniazda ładowania w aucie elektrycznym",
    "Wymiana płynu chłodniczego w aucie elektrycznym",
    "Wymiana akumulatora w aucie elektrycznym",
    "Wymiana przewodów wysokiego napięcia w aucie elektrycznym",
    "Wymiana silnika w aucie elektrycznym",
    "Auta hybrydowe",
    "Wymiana baterii w układzie hybrydowym",
    "Kontrola akumulatora pojazdu hybrydowego",
    "Diagnostyka napędu hybrydowego",
    "Naprawa przekładni w aucie hybrydowym",
    "Naprawa silnika elektrycznego w aucie hybrydowym",
    "Regeneracja baterii w aucie hybrydowym",
    "Wymiana falownika w aucie hybrydowym",
    "Wymiana gniazda do ładowania w hybrydzie typu plug-in",
    "Wymiana płynu chłodniczego w aucie hybrydowym",
    "Wymiana przewodów wysokiego napięcia w aucie hybrydowym"
]




prices_car = {
    "Wymiana oleju i filtra oleju": 100,
    "Wymiana filtra powietrza": 50,
    "Wymiana filtra paliwa": 70,
    "Wymiana filtra kabinowego": 60,
    "Hamulce": 150,
    "Naprawa układu hamulcowego": 200,
    "Wymiana klocków hamulcowych": 100,
    "Wymiana tarcz hamulcowych": 120,
    "Wymiana szczęk hamulcowych": 90,
    "Wymiana cylinderków hamulcowych w samochodzie": 80,
    "Wymiana bębnów hamulcowych": 100,
    "Wymiana tarcz kotwicznych bębnów hamulcowych": 110,
    "Wymiana rozpieraczy": 50,
    "Wymiana linki hamulca ręcznego": 70,
    "Wymiana przewodów hamulcowych elastycznych": 80,
    "Wymiana przewodów hamulcowych metalowych": 90,
    "Wymiana pompy hamulcowej": 120,
    "Wymiana płynu hamulcowego": 40,
    "Naprawa ABS": 250,
    "Wymiana pompy ABS": 300,
    "Wymiana czujnika ABS": 150,
    "Weryfikacja układu hamulcowego": 70,
    "Zawieszenie": 200,
    "Wymiana drążka kierowniczego": 120,
    "Wymiana końcówki drążka kierowniczego": 100,
    "Wymiana maglownicy": 300,
    "Wymiana zwrotnicy koła": 150,
    "Wymiana krzyżaka kolumny kierowniczej": 180,
    "Wymiana pompy wspomagania": 250,
    "Wymiana płynu wspomagania kierownicy": 40,
    "Naprawa układu kierowniczego": 200,
    "Wymiana osłony elastycznej przekładni kierowniczej": 80,
    "Ustawienie geometrii i zbieżności kół": 100,
    "Wymiana stabilizatora": 150,
    "Wymiana łącznika stabilizatora": 80,
    "Wymiana tulejek gumy stabilizatora": 90,
    "Wymiana wahacza": 180,
    "Wymiana silentblocku wahacza": 100,
    "Wymiana sworznia wahacza": 80,
    "Wymiana amortyzatora": 150,
    "Wymiana łożyska amortyzatora": 70,
    "Wymiana poduszki amortyzatora": 60,
    "Wymiana osłony elastycznej amortyzatora": 50,
    "Wymiana sprężyn zawieszenia": 120,
    "Wymiana kolumny MacPhersona": 200,
    "Wymiana piasty": 180,
    "Wymiana łożyska w kole": 100,
    "Naprawa zawieszenia": 250,
    "Weryfikacja układu kierowniczego": 80,
    "Diagnostyka zawieszenia": 100,
    "Silnik": 300,
    "Wymiana paska wielorowkowego": 80,
    "Wymiana paska rozrządu": 150,
    "Wymiana łańcucha rozrządu": 200,
    "Wymiana płynu chłodniczego": 60,
    "Wymiana chłodnicy silnika": 250,
    "Wymiana czujnika temperatury": 50,
    "Wymiana termostatu": 70,
    "Naprawa wentylatora chłodnicy": 100,
    "Wymiana nagrzewnicy": 120,
    "Wymiana przewodów układu chłodzenia w samochodzie": 80,
    "Wymiana pompy wody": 150,
    "Wymiana sprzęgła wentylatora chłodnicy (wiskozy)": 180,
    "Wymiana rezystora nagrzewnicy": 70,
    "Wymiana czujnika / termowłącznika wentylatora": 60,
    "Naprawa układu chłodzenia": 200,
    "Wymiana kolektora dolotowego": 220,
    "Wymiana uszczelki kolektora dolotowego": 100,
    "Wymiana przewodu dolotowego": 150,
    "Wymiana uszczelki przewodu dolotowego": 80,
    "Wymiana przepływomierza - czujnika masy powietrza": 120,
    "Naprawa układu dolotowego": 180,
    "Wymiana wtryskiwaczy": 200,
    "Wymiana pompowtryskiwaczy": 250,
    "Wymiana pompy paliwa": 180,
    "Wymiana pompy wtryskowej": 300,
    "Wymiana zbiornika paliwa": 160,
    "Wymiana przewodów paliwowych": 100,
    "Czyszczenie układu paliwowego": 80,
    "Naprawa układu paliwowego": 250,
    "Wymiana uszczelki pokrywy zaworów": 90,
    "Wymiana uszczelki miski olejowej": 80,
    "Wymiana uszczelki pod głowicą": 150,
    "Wymiana uszczelniaczy zaworowych": 120,
    "Wymiana napinacza paska klinowego": 70,
    "Wymiana linki gazu": 100,
    "Wymiana koła pasowego": 80,
    "Wymiana rolki napinacza": 60,
    "Wymiana rolki napinającej": 70,
    "Wymiana silnika regulacji biegu jałowego": 200,
    "Wymiana rozrządu": 250,
    "Wymiana zaworów": 500,
    "Wymiana pierścieni tłokowych": 700,
    "Wymiana sworznia tłokowego": 150,
    "Wymiana panewek korbowodowych": 300,
    "Wymiana panewek": 250,
    "Wymiana tłoków": 600,
    "Wymiana wałka rozrządu": 400,
    "Wymiana wału korbowego": 800,
    "Planowanie głowicy": 300,
    "Generalny remont silnika": 2000,
    "Naprawa silnika": 1500,
    "Wymiana koła zamachowego": 350,
    "Wymiana turbosprężarki": 1000,
    "Weryfikacja silnika": 100,
    "Weryfikacja układu chłodzenia": 50,
    "Weryfikacja układu paliwowego": 50,
    "Naprawa wtryskiwacza paliwa": 200,
    "Regeneracja głowic samochodowych": 600,
    "Układ napędowy": 300,
    "Wymiana półosi": 250,
    "Wymiana uszczelniacza półosi napędowej": 100,
    "Wymiana przegubu": 150,
    "Wymiana osłony przegubu": 80,
    "Naprawa układu napędowego": 400,
    "Wymiana oleju w mechanizmie różnicowym": 150,
    "Naprawa wałów i mostów napędowych": 500,
    "Weryfikacja układu napędowego": 100,
    "Naprawa skrzyń biegów": 800,
    "Wymiana oleju w skrzyni automatycznej": 300,
    "Wymiana oleju i filtra w skrzyni manualnej": 200,
    "Wymiana sprzęgła": 400,
    "Wymiana kompletnego sprzęgła z dwumasowym kołem zamachowym": 800,
    "Wymiana tarczy sprzęgła": 250,
    "Wymiana docisku sprzęgła": 150,
    "Wymiana łożyska oporowego sprzęgła": 180,
    "Wymiana linki sprzęgła": 100,
    "Wymiana wysprzęglika": 200,
    "Wymiana pompy sprzęgła": 350,
    "Wymiana oleju i filtra hydraulicznego w skrzyni automatycznej": 400,
    "Naprawa automatycznej skrzyni biegów": 1500,
    "Naprawa manualnej skrzyni biegów": 1000,
    "Układ wydechowy": 200,
    "Wymiana kolektora wydechowego": 300,
    "Wymiana uszczelki kolektora wydechowego": 80,
    "Wymiana kompletnego tłumika": 400,
    "Wymiana tłumika środkowego": 250,
    "Wymiana tłumika końcowego": 300,
    "Wymiana tłumika drgań": 200,
    "Spawanie tłumika": 150,
    "Uszczelnianie wydechu": 100,
    "Naprawa wieszaków tłumika": 80,
    "Wymiana katalizatora": 500,
    "Wymiana sondy lambda": 200,
    "Wymiana filtra DPF": 800,
    "Naprawa układu wydechowego": 300,
    "Wymiana zaworu EGR": 350,
    "Weryfikacja układu wydechowego": 100,
    "Regeneracja filtra cząstek stałych DPF / FAP": 800,
    "Regeneracja części samochodowych": 200,
    "Regeneracja pompy hamulcowej": 300,
    "Regeneracja pompy ABS": 350,
    "Regeneracja przekładni kierowniczej": 400,
    "Regeneracja pompy wspomagania": 300,
    "Regeneracja wtryskiwaczy benzynowych i diesla": 250,
    "Regeneracja pompy wtryskowej": 500,
    "Regeneracja turbosprężarki": 1000,
    "Regeneracja alternatora": 400,
    "Regeneracja rozrusznika": 300,
    "Regeneracja zacisków hamulcowych": 150,
    "Elektronika": 300,
    "Serwis Akumulatorów": 100,
    "Wymiana akumulatora": 200,
    "Sprawdzenie ładowania akumulatora": 50,
    "Test obciążeniowy akumulatora": 80,
    "Dostawa akumulatora z wymianą": 250,
    "Darmowy test akumulatora": 0,
    "Diagnostyka": 150,
    "Kasowanie kodów błędów": 80,
    "Oświetlenie": 100,
    "Wymiana żarówki reflektora (Przód)": 50,
    "Ustawienie świateł": 80,
    "Wymiana tylnego klosza": 30,
    "Wymiana silnika regulacji wysokości świateł": 150,
    "Wymiana żarówki tablicy rejestracyjnej": 20,
    "Elektryka samochodowa": 200,
    "Wymiana żarówki klosza (Tył)": 40,
    "Wymiana żarówki ksenonowej": 100,
    "Montaż czujników parkowania": 150,
    "Wymiana zegarów deski rozdzielczej": 250,
    "Wymiana świec zapłonowych/żarowych": 100,
    "Wymiana przewodów zapłonowych": 80,
    "Wymiana cewki zapłonowej": 150,
    "Naprawa modułu zapłonowego": 200,
    "Wymiana kopułki rozdzielacza": 50,
    "Naprawa rozdzielacza": 150,
    "Wymiana rozrusznika": 200,
    "Wymiana alternatora": 300,
    "Montaż kamery cofania": 200,
    "Wymiana bezpieczników": 30,
    "Wymiana silniczka wycieraczek": 80,
    "Wymiana pompy spryskiwacza": 100,
    "Wymiana przerywnika kierunkowskazów": 50,
    "Montaż elektrycznego ogrzewania postojowego DEFA": 500,
    "Montaż spalinowego ogrzewania postojowego typu Webasto": 800,
    "Wymiana mechanizmu podnoszenia szyby": 150,
    "Wymiana stacyjki": 200,
    "Naprawa i wymiana zamków": 150,
    "Wymiana cięgna wycieraczki": 80,
    "Montaż siłowników centralnego zamka": 200,
    "Wymiana nagrzewnicy silnika": 300,
    "Naprawa liczników samochodowych": 250,
    "Naprawa systemu wspomagającego hamowanie - ABS, BAS, EBD": 300,
    "Naprawa systemu zapobiegającego poślizgom - ASR, ESP, DSR, RSC, VSA": 350,
    "Naprawa systemu wspomagającego jazdę - TSR, ACC, BLIS, AFS, LDW, HHC, SBR": 400,
    "Naprawa systemu wspomagającego układ napędowy - ACD, EDS": 400,
    "Naprawa systemu bezpieczeństwa podczas wypadku - AHR, ACS": 300,
    "Elektryk samochodowy - naprawa elektroniki": 250,
    "Wymiana czujnika biegu jałowego": 100,
    "Wymiana czujnika ciśnienia oleju": 80,
    "Wymiana czujnika ciśnienia paliwa": 80,
    "Wymiana czujnika ciśnienia powietrza w kole TPMS": 100,
    "Wymiana czujnika ciśnienia spalin": 100,
    "Wymiana czujnika ciśnienia w kolektorze ssącym": 80,
    "Wymiana czujnika ciśnienia w układzie hamulcowym": 100,
    "Wymiana czujnika ciśnienia modułu tłoczącego DeNOx": 150,
    "Wymiana czujnika Halla aparatu zapłonowego i wału korbowego": 120,
    "Wymiana czujnika i nadajnika układu sterowania wtryskiem paliwa": 150,
    "Wymiana czujnika impulsów / impulsatora": 100,
    "Wymiana czujnika klimatyzacji": 100,
    "Wymiana czujnika ciśnienia gazu (LPG)": 120,
    "Wymiana czujnika nachylenia, układu alarmowego": 100,
    "Wymiana czujnika obrotomierza": 80,
    "Wymiana czujnika oleju": 80,
    "Wymiana czujnika otwierania drzwi": 80,
    "Wymiana czujnika położenia pedału gazu": 100,
    "Wymiana czujnika położenia pedału sprzęgła": 100,
    "Wymiana czujnika położenia przepustnicy": 100,
    "Wymiana czujnika położenia wałka rozrządu": 120,
    "Wymiana czujnika położenia wału korbowego": 120,
    "Wymiana czujnika poziomu oleju silnikowego": 80,
    "Wymiana czujnika poziomu paliwa": 80,
    "Wymiana czujnika poziomu płynu chłodzącego": 80,
    "Wymiana czujnika poziomu płynu hamulcowego": 80,
    "Wymiana czujnika poziomu płynu spryskiwacza": 80,
    "Wymiana czujnika poziomu zawieszenia pneumatycznego": 120,
    "Wymiana czujnika przesunięcia pedału hamulca": 100,
    "Wymiana czujnika skrętu koła kierownicy": 100,
    "Wymiana czujnika skrzyni biegów": 100,
    "Wymiana czujnika spalania stukowego": 100,
    "Wymiana czujnika szybkości": 100,
    "Wymiana czujnika świateł stop": 80,
    "Wymiana czujnika temperatury wewnętrznej klimatyzacji": 100,
    "Wymiana czujnika temperatury oleju": 80,
    "Wymiana czujnika temperatury paliwa": 80,
    "Wymiana czujnika temperatury płynu chłodzącego": 80,
    "Wymiana czujnika temperatury powietrza wlotowego": 80,
    "Wymiana czujnika temperatury spalin": 100,
    "Wymiana czujnika temperatury zewnętrznej": 80,
    "Wymiana czujnika tlenków azotu NOx": 150,
    "Wymiana czujnika układu chłodzenia": 80,
    "Wymiana czujnika zużycia klocka hamulcowego": 100,
    "Wymiana czujnika/przekaźnika": 80,
    "Weryfikacja instalacji elektrycznej": 150,
    "Zaawansowane systemy wspomagania kierowcy (ADAS)": 400,
    "Tempomat montaż i naprawa": 300,
    "Kalibracja radarów": 500,
    "Ustawienia kamery samochodowej": 200,
    "System wspomagający ruszanie pod górę (HAS)": 300,
    "Elektroniczny system bezpieczeństwa czynnego (Hill Descent Control)": 350,
    "System stabilizujący tor jazdy samochodu (ESC)": 400,
    "Czujniki ciśnienia w oponach TPMS - wymiana": 100,
    "Naprawa i wymiana opon": 50,
    "Wymiana opon Runflat - dowolna felga": 100,
    "Wymiana opon z czujnikiem TPMS": 120,
    "Wymiana opon i wulkanizacja": 80,
    "Naprawa opon": 30,
    "Wymiana zaworków": 50,
    "Wyważanie kół": 40,
    "Geometria kół 3D": 100,
    "Mobilna wulkanizacja 24h": 150,
    "Naprawa felg": 80,
    "Renowacja felg stalowych": 100,
    "Renowacja felg aluminiowych": 120,
    "Diagnostyka komputerowa samochodu": 150,
    "Przegląd podstawowy": 100,
    "Przegląd rozszerzony": 200,
    "Przegląd samochodu przed zakupem": 250,
    "Przegląd letni": 100,
    "Przegląd zimowy": 120,
    "Przegląd samochodu przed podróżą": 150,
    "Pomiar punktów bazowych nadwozia": 80,
    "Diagnostyka samochodu - 22 punkty kontrolne": 120,
    "Diagnostyka samochodu - 29 punktów kontrolnych": 150,
    "Przegląd przed wakacjami": 200,
    "Stacja Kontroli Pojazdów": 150,
    "Przegląd - okresowe badanie techniczne (SKP)": 200,
    "Klimatyzacja": 300,
    "Serwis klimatyzacji": 250,
    "Przegląd klimatyzacji": 150,
    "Napełnienie klimatyzacji": 100,
    "Sprawdzenie szczelności układu klimatyzacji - ciśnieniowe": 120,
    "Sprawdzenie szczelności układu klimatyzacji - ultrafiolet": 150,
    "Odgrzybianie klimatyzacji": 100,
    "Ozonowanie klimatyzacji": 200,
    "Wymiana oleju w sprężarce klimatyzacji": 150,
    "Serwis klimatyzacji samochodowej": 250,
    "Naprawa układu klimatyzacji": 300,
    "Blacharstwo i lakiernictwo": 200,
    "Wymiana elementów blacharskich": 150,
    "Wymiana zderzaka": 200,
    "Wymiana błotnika": 250,
    "Wymiana pokrywy silnika": 150,
    "Wymiana klapy bagażnika": 200,
    "Wymiana drzwi przednich": 250,
    "Wymiana drzwi tylnych": 250,
    "Wymiana dachu": 300,
    "Wymiana ćwiartki przedniej": 200,
    "Wymiana ćwiartki tylnej": 200,
    "Wymiana progu": 150,
    "Wymiana pasa przedniego": 100,
    "Wymiana pasa tylnego": 100,
    "Wymiana reflektora": 150,
    "Wymiana kierunkowskazu": 100,
    "Wymiana lusterka": 100,
    "Wymiana nadkola": 150,
    "Wymiana podłogi pod silnikiem": 200,
    "Naprawa zderzaka": 100,
    "Naprawa błotnika": 150,
    "Naprawa pokrywy silnika": 100,
    "Naprawa tylnej klapy": 150,
    "Naprawa drzwi przednich": 200,
    "Naprawa drzwi tylnych": 200,
    "Naprawa dachu": 500,
    "Naprawa przedniej ćwiartki": 300,
    "Naprawa tylnej ćwiartki": 300,
    "Naprawa progu": 200,
    "Naprawa pasa przedniego": 200,
    "Naprawa pasa tylnego": 200,
    "Wymiana teleskopu pokrywy silnika lub klapy bagażnika": 150,
    "Wyciąganie wgniotek": 100,
    "Konserwacja podwozia / zabezpieczenie antykorozyjne podwozia": 300,
    "Lakierowanie elementów blacharskich": 250,
    "Lakiernik samochodowy - lakierowanie całego nadwozia": 2000,
    "Lakierowanie zderzaka przedniego": 300,
    "Lakierowanie zderzaka tylnego": 300,
    "Lakierowanie błotnika przedniego": 400,
    "Lakierowanie błotnika tylnego": 400,
    "Malowanie pokrywy silnika": 300,
    "Lakierowanie tylnej klapy": 500,
    "Lakierowanie drzwi przednich": 300,
    "Lakierowanie drzwi tylnych": 300,
    "Lakierowanie dachu": 600,
    "Lakierowanie ćwiartki przedniej": 400,
    "Lakierowanie ćwiartki tylnej": 400,
    "Malowanie progu": 200,
    "Lakierowanie pasa przedniego": 300,
    "Lakierowanie pasa tylnego": 300,
    "Lakierowanie lusterka": 150,
    "Zabezpieczenie antykorozyjne": 250,
    "Wymiana szyb": 300,
    "Wymiana czujnika opadów deszczu": 150,
    "Wymiana szyby przedniej": 400,
    "Wymiana szyby tylnej": 350,
    "Wymiana, naprawa szyberdachu": 500,
    "Wymiana szkła lusterka": 120,
    "Wymiana szyby karoseryjnej": 450,
    "Naprawa szyb": 100,
    "Naprawa podgrzewania szyby przedniej / tylnej": 200,
    "Wymiana szyby bocznej - otwieranej": 250,
    "Naprawa pęknięć/odprysków szyb": 80,
    "Czyszczenie auta": 150,
    "Przyciemnianie szyb": 200,
    "Przyciemnianie szyby szyberdachu": 250,
    "Niewidzialna wycieraczka": 180,
    "Regeneracja reflektorów": 100,
    "Czyszczenie wnętrza samochodu": 120,
    "Polerowanie i woskowanie samochodu": 300,
    "Oklejanie samochodu": 400,
    "Pranie tapicerki samochodowej": 200,
    "Polerowanie samochodu": 250,
    "Myjnia samochodowa": 80,
    "Myjnia parowa": 150,
    "Myjnia bezdotykowa": 100,
    "Myjnia ręczna": 70,
    "Myjnia samoobsługowa": 50,
    "Pranie tapicerki": 120,
    "Uruchomienie samochodu w zimie u klienta": 50,
    "Awaryjne otwieranie samochodu": 100,
    "Serwis instalacji gazowych LPG": 300,
    "Montaż instalacji LPG": 1500,
    "Regulacja LPG": 200,
    "Wymiana elektrozaworu LPG": 250,
    "Wymiana filtra LPG": 120,
    "Wymiana mieszalnika LPG": 180,
    "Wymiana przewodów LPG": 300,
    "Wymiana reduktora LPG": 400,
    "Wymiana zaworu LPG": 200,
    "Wymiana wlewu LPG": 150,
    "Wymiana wtryskiwacza LPG": 350,
    "Wymiana parownika LPG": 500,
    "Lubryfikacja LPG": 100,
    "Legalizacja zbiornika LPG": 200,
    "Wymiana butli LPG": 800,
    "Serwis instalacji gazowych CNG": 400,
    "Regulacja CNG": 250,
    "Wymiana wtryskiwacza CNG": 300,
    "Montaż instalacji CNG z homologacją": 2000,
    "Wymiana reduktora CNG": 500,
    "Wymiana przewodów CNG": 400,
    "Wymiana elektrozaworu CNG": 350,
    "Wymiana mieszalnika CNG": 300,
    "Wymiana wlewu CNG": 250,
    "Wymiana zaworu CNG": 200,
    "Wymiana parownika CNG": 600,
    "Wymiana zbiornika CNG": 1500,
    "Lubryfikacja CNG": 150,
    "Legalizacja zbiornika CNG": 500,
    "Modyfikacje/Tuning": 1000,
    "Tuning samochodów i modyfikacje sportowe": 1200,
    "Pompowanie opon azotem": 30,
    "Montaż Power Boxów podnoszących moc": 400,
    "Podniesienie mocy silnika": 800,
    "Montaż sportowego filtra powietrza": 150,
    "Montaż sportowego filtra oleju": 100,
    "Montaż opon wyczynowych": 50,
    "Obsługa hamulców sportowych": 200,
    "Montaż sportowych tarcz hamulcowych": 250,
    "Montaż sportowych klocków hamulcowych": 200,
    "Montaż sportowego płynu hamulcowego": 150,
    "Montaż przewodów hamulcowych w oplocie": 100,
    "Obsługa zawieszenia sportowego": 300,
    "Montaż sportowych amortyzatorów": 400,
    "Obniżenie samochodu": 500,
    "Montaż sprężyn do zwiększonego obciążenia": 350,
    "Montaż rozpórek": 100,
    "Montaż sportowych stabilizatorów": 300,
    "Montaż sportowych tulei zawieszenia": 150,
    "Montaż sportowego zestawu zawieszenia": 600,
    "Montaż sportowych wskaźników": 80,
    "Instalacja podtlenku azotu": 600,
    "Montaż oświetlenia ksenonowego": 200,
    "Montaż kutych tłoków": 400,
    "Montaż wyczynowych panewek": 300,
    "Montaż wyczynowych zaworów": 500,
    "Montaż sportowego wałka rozrządu": 450,
    "Montaż sportowych świec zapłonowych": 120,
    "Montaż sportowych przewodów zapłonowych": 150,
    "Montaż sportowego układu chłodzenia": 600,
    "Adaptacja regulatora ciśnienia paliwa": 200,
    "Montaż sportowej pompy paliwa": 300,
    "Montaż sportowego układu wydechowego": 700,
    "Montaż sportowego układu przeniesienia napędu": 800,
    "Wymiana sportowego oleju silnikowego": 100,
    "Wymiana sportowego oleju przekładniowego": 150,
    "Wymiana sportowego płynu chłodzącego": 120,
    "Detale samochodu": 150,
    "Dekarbonizacja (wodorowanie) silnika": 250,
    "Hamownia samochodowa": 300,
    "Tapicer samochodowy": 200,
    "Chiptuning / mapowanie silnika": 500,
    "Akcesoria samochodowe": 80,
    "Montaż belek dachowych": 100,
    "Montaż boxu dachowego": 200,
    "Montaż haka holowniczego": 150,
    "Wymiana pasa bezpieczeństwa": 100,
    "Wymiana piór wycieraczek": 50,
    "Wymiana Gaśnicy": 80,
    "Kodowanie / programowanie kluczyka": 120,
    "Car Audio": 150,
    "Montaż radia": 80,
    "Montaż nawigacji": 100,
    "Montaż głośników samochodowych": 120,
    "Wygłuszenie samochodu": 200,
    "Podłączenie wzmacniacza samochodowego": 150,
    "Podłączenie subwoofera": 180,
    "Montaż anten": 50,
    "Aktualizacja nawigacji": 80,
    "Montaż zestawu głośnomówiącego": 100,
    "Montaż systemu GPS": 150,
    "Pojazdy elektryczne i hybrydowe": 500,
    "Układy samochodów elektrycznych": 600,
    "Kontrola akumulatora wysokonapięciowego pojazdu elektrycznego": 200,
    "Regeneracja baterii w aucie elektrycznym": 800,
    "Diagnostyka silnika elektrycznego": 250,
    "Naprawa przekładni w aucie elektrycznym": 400,
    "Wymiana falownika w aucie elektrycznym": 500,
    "Naprawa silnika w aucie elektrycznym": 1000,
    "Wymiana gniazda ładowania w aucie elektrycznym": 150,
    "Wymiana płynu chłodniczego w aucie elektrycznym": 100,
    "Wymiana akumulatora w aucie elektrycznym": 300,
    "Wymiana przewodów wysokiego napięcia w aucie elektrycznym": 200,
    "Wymiana silnika w aucie elektrycznym": 1500,
    "Auta hybrydowe": 600,
    "Wymiana baterii w układzie hybrydowym": 250,
    "Kontrola akumulatora pojazdu hybrydowego": 100,
    "Diagnostyka napędu hybrydowego": 200,
    "Naprawa przekładni w aucie hybrydowym": 300,
    "Naprawa silnika elektrycznego w aucie hybrydowym": 500,
    "Regeneracja baterii w aucie hybrydowym": 600,
    "Wymiana falownika w aucie hybrydowym": 400,
    "Wymiana gniazda do ładowania w hybrydzie typu plug-in": 150,
    "Wymiana płynu chłodniczego w aucie hybrydowym": 120,
    "Wymiana przewodów wysokiego napięcia w aucie hybrydowym": 180}


with open('uslugi_samochodowe.csv', mode='w', newline='', encoding='utf-8') as file:
    writer = csv.writer(file)
    writer.writerow(['Usluga', 'Cena'])
    for usluga in services_car:
        writer.writerow([usluga, prices_car.get(usluga, 'Brak danych')])
